# Generated by Django 6.0.2 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
