# Generated by Django 6.0.2 on 2026-03-03 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.URLField(blank=True, default='', verbose_name='Картинка (URL)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='О маршруте')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дни)')),
                ('max_slots', models.PositiveIntegerField(default=15, verbose_name='Мест в группе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_city', models.CharField(default='Бишкек', max_length=80, verbose_name='Город вылета')),
                ('vacation_type', models.CharField(choices=[('Любой', 'Любой'), ('Пляжный', 'Пляжный'), ('Экскурсионный', 'Экскурсионный'), ('Горнолыжный', 'Горнолыжный'), ('Семейный', 'Семейный'), ('Шопинг', 'Шопинг')], default='Любой', max_length=40, verbose_name='Вид отдыха')),
                ('visa_required', models.BooleanField(default=False, verbose_name='Нужна виза')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.country', verbose_name='Страна')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
