# Generated by Django 6.0.2 on 2026-03-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='vacation_type',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='visa_required',
        ),
        migrations.AddField(
            model_name='country',
            name='vacation_type',
            field=models.CharField(choices=[('any', 'Любой'), ('sea', 'Море'), ('mountains', 'Горы'), ('city', 'Город'), ('ski', 'Горнолыжный'), ('excursion', 'Экскурсионный')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.country'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure_city',
            field=models.CharField(choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('almaty', 'Алматы')], default='bishkek', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_slots',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='tour',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
