# Generated by Django 6.0.2 on 2026-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_vacation_type_remove_tour_visa_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='short_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
