# Generated by Django 6.0.2 on 2026-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_country_about_remove_country_short_info_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.AddField(
            model_name='country',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='short_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
