# Generated by Django 6.0.2 on 2026-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_city_tour_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1507525428034-b723cf961d3e'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
