# Generated by Django 6.0.2 on 2026-03-03 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['iata'],
            },
        ),
        migrations.CreateModel(
            name='FlightOfferCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('cabin', models.CharField(default='ECONOMY', max_length=16)),
                ('provider', models.CharField(default='stub', max_length=40)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['origin', 'destination', 'depart_date', 'return_date', 'adults', 'cabin'], name='flights_fli_origin_d8fab7_idx'), models.Index(fields=['expires_at'], name='flights_fli_expires_1e0e55_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('cabin', models.CharField(default='ECONOMY', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
