# Generated by Django 6.0.2 on 2026-03-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0008_tour_departure_time_tour_details_tour_hotel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attraction_type', models.CharField(choices=[('museum', 'Музей'), ('monument', 'Памятник'), ('park', 'Парк'), ('church', 'Церковь'), ('nature', 'Природа'), ('other', 'Другое')], default='other', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0, help_text='Рейтинг от 0 до 5')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tours.country')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='CountryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('fact_type', models.CharField(choices=[('historical', 'Исторический'), ('geographical', 'Географический'), ('cultural', 'Культурный'), ('other', 'Другое')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='tours.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('festival', 'Фестиваль'), ('exhibition', 'Выставка'), ('concert', 'Концерт'), ('sport', 'Спорт'), ('other', 'Другое')], default='other', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('rating', models.FloatField(default=0, help_text='Рейтинг от 0 до 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tours.country')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('category', models.CharField(choices=[('museum', 'Музей'), ('nature', 'Природа'), ('event', 'Событие'), ('other', 'Другое')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tours.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
