# Generated by Django 6.0.2 on 2026-03-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
    ]
