# Generated by Django 6.0.2 on 2026-03-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_add_all_countries_data'),
        ('info', '0002_add_initial_data'),
    ]

    operations = [
    ]
