# Generated by Django 6.0.2 on 2026-03-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_airport', models.CharField(blank=True, max_length=255)),
                ('arrival_airport', models.CharField(blank=True, max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=50)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_notifications', to='bookings.bookingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
