# Generated by Django 6.0.2 on 2026-03-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tournotification_currency_tournotification_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournotification',
            options={},
        ),
    ]
