# Generated by Django 6.0.2 on 2026-03-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_tournotification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tournotification',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tournotification',
            name='price',
        ),
    ]
