# Generated by Django 6.0.2 on 2026-03-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_tournotification_currency_chatnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournotification',
            name='currency',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
